### ISSUE TITLE
Check if mediaversion is 0, use the "FALLBACK" key.

### ISSUE THREAD

**Issue by zadlg** [reversing-research/deezer-download#10]
I've discovered something about mediaversion : if mediaversion == 0, the song doesn't exists.

Example with that song : https://www.deezer.com/track/100618424

We got that dl link : http://e-cdn-proxy-6.deezer.com/mobile/1/7ba52a53997044157a3364cf45face341cd9958222ff5594523f7bd497795687f4510e8025a1a5146f0bb3d93d14ca11bc955b9b7c316b3026366cc10f33ab48b4801dc9443956b71adb7674fb07aab7   which is correct, but Deezer returns a 403 error.
I've investigated and I saw that mediaversion of "100618424" is 0 : 

`{"data":[{"SNG_ID":"100618424","PRODUCT_TRACK_ID":"132980961","UPLOAD_ID":0,"SNG_TITLE":"West Side Lane","ART_ID":"1658358","PROVIDER_ID":"4","ART_NAME":"Lost Years","ARTISTS":[{"ART_ID":"1658358","ROLE_ID":"0","ARTISTS_SONGS_ORDER":"1","ART_NAME":"Lost Years","ART_PICTURE":"93746bd189e95cb64e83f99c6c4907fc","SMARTRADIO":"1","RANK":"179265","__TYPE__":"artist"}],"ALB_ID":"10336518","ALB_TITLE":"Kung Fury","TYPE":0,"MD5_ORIGIN":"651dc7dbe1749f8e0824ddfdfae8eb90","VIDEO":false,"DURATION":"230","ALB_PICTURE":"5f2f7ff89098a72de8d79ddc944222df","ART_PICTURE":"93746bd189e95cb64e83f99c6c4907fc","RANK_SNG":"299077","SMARTRADIO":"1","FILESIZE_AAC_64":0,"FILESIZE_MP3_64":"1845706","FILESIZE_MP3_128":"3691414","FILESIZE_MP3_256":0,"FILESIZE_MP3_320":"9228537","FILESIZE":"3691414","MEDIA_VERSION":"0","DISK_NUMBER":"1","TRACK_NUMBER":"3","VERSION":"","EXPLICIT_LYRICS":"0","RIGHTS":{},"ISRC":"USQY51302961","HIERARCHICAL_TITLE":"","SNG_CONTRIBUTORS":{"mainartist":["Lost Years"],"producer":["Magnus Larsson"],"composer":["Magnus Larsson"],"author":["Magnus Larsson"],"musicpublisher":["Copyright Control"]},"LYRICS_ID":0,"FALLBACK":{"SNG_ID":"63304661","PRODUCT_TRACK_ID":"132980961","UPLOAD_ID":0,"SNG_TITLE":"West Side Lane","ART_ID":"1658358","PROVIDER_ID":"49","ART_NAME":"Lost Years","ARTISTS":[{"ART_ID":"1658358","ROLE_ID":"0","ARTISTS_SONGS_ORDER":"0","ART_NAME":"Lost Years","ART_PICTURE":"93746bd189e95cb64e83f99c6c4907fc","SMARTRADIO":"1","RANK":"179265","__TYPE__":"artist"}],"ALB_ID":"6218183","ALB_TITLE":"Black Waves","TYPE":0,"MD5_ORIGIN":"0252a8e8817ff6a5136bb741ac555bf2","VIDEO":false,"DURATION":"229","ALB_PICTURE":"c5bde24341316cea53ab0693913b8a46","ART_PICTURE":"93746bd189e95cb64e83f99c6c4907fc","RANK_SNG":"291835","SMARTRADIO":"1","FILESIZE_AAC_64":0,"FILESIZE_MP3_64":"0","FILESIZE_MP3_128":"3668878","FILESIZE_MP3_256":0,"FILESIZE_MP3_320":"9164800","FILESIZE":"3668878","MEDIA_VERSION":"0","DISK_NUMBER":"1","TRACK_NUMBER":"5","VERSION":"","EXPLICIT_LYRICS":"0","RIGHTS":{"STREAM_ADS_AVAILABLE":true,"STREAM_ADS":"2000-01-01","STREAM_SUB_AVAILABLE":true,"STREAM_SUB":"2000-01-01","DOWNLOAD_ALC":"2000-01-01","DOWNLOAD_ALC_AVAILABLE":true},"ISRC":"USQY51302961","HIERARCHICAL_TITLE":"","SNG_CONTRIBUTORS":[],"LYRICS_ID":0,"COPYRIGHT":"2012 (c) 2012 Rosso Corsa Records","PHYSICAL_RELEASE_DATE":"2013-06-30","S_MOD":1,"S_PREMIUM":1,"DATE_START_PREMIUM":"2000-01-01","DATE_START":"2000-01-01","STATUS":1,"USER_ID":0,"URL_REWRITING":"lost-years","SNG_STATUS":"1","AVAILABLE_COUNTRIES":{"STREAM_ADS":["AD","AE","AF","AG","AI","AL","AM","AN","AO","AQ","AR","AS","AT","AU","AW","AX","AZ","BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BR","BS","BT","BV","BW","BY","BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN","CO","CR","CU","CV","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","EH","ER","ES","ET","FI","FJ","FK","FM","FO","FR","GA","GB","GD","GE","GF","GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY","HK","HM","HN","HR","HT","HU","ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE","JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ","LA","LB","LC","LI","LK","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME","MF","MG","MH","MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ","NA","NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ","OM","PA","PE","PF","PG","PH","PK","PL","PM","PN","PR","PS","PT","PW","PY","QA","RE","RO","RS","RU","RW","SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","ST","SV","SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN","TO","TR","TT","TV","TW","TZ","UA","UG","UM","US","UY","UZ","VA","VC","VE","VG","VI","VN","VU","WF","WS","YE","YT","ZA","ZM","ZW"],"STREAM_SUB_ONLY":[]},"__TYPE__":"song"},"COPYRIGHT":"(C) 2015 Universal Music AB","PHYSICAL_RELEASE_DATE":"2015-05-29","S_MOD":0,"S_PREMIUM":0,"DATE_START_PREMIUM":"0000-00-00","DATE_START":"0000-00-00","STATUS":1,"USER_ID":0,"URL_REWRITING":"lost-years","SNG_STATUS":"1","AVAILABLE_COUNTRIES":{"STREAM_ADS":[],"STREAM_SUB_ONLY":[]},"__TYPE__":"song","DIGITAL_RELEASE_DATE":"2013-06-30"}],"count":1,"total":1}`

But if we look into the "FALLBACK" key, we can see that it's not empty, and actually contains the "real song" with a mediaversion which is not null.

**Comment by reversing-research** [comment]
Thanks.

This seems to happen when the same song is on multiple albums.

I will make a fix.

**Comment by reversing-research** [comment]
now fixed.   you may encounter the problem now that deezer-download.py will note that you already saved the file. ... this is because sometimes the fallbacksong is by itself also listed as a seperate song on the same page. but with a different SNG_ID.
